-- Log veritabanı (LogConnectionStrings / portallogdb) üzerinde çalıştırın.
-- Tüm log tabloları için: CreatePortalLogDbTables.sql (RequestUrl, Sessions, Errors, …)
-- Hata: 42P01 relation "UserActivityLogs" does not exist
-- EF Core: DbSet<UserActivity> UserActivityLogs -> tablo adı "UserActivityLogs"

CREATE TABLE IF NOT EXISTS "UserActivityLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SessionId" bigint NOT NULL,
    "RequestUrlId" bigint NOT NULL,
    "Payload" text,
    "StatusCode" integer NOT NULL,
    "Time" timestamp without time zone NOT NULL,
    "Response" text,
    CONSTRAINT "PK_UserActivityLogs" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_UserActivityLogs_Time" ON "UserActivityLogs" ("Time" DESC);
CREATE INDEX IF NOT EXISTS "IX_UserActivityLogs_SessionId" ON "UserActivityLogs" ("SessionId");
CREATE INDEX IF NOT EXISTS "IX_UserActivityLogs_RequestUrlId" ON "UserActivityLogs" ("RequestUrlId");
