-- portallogdb (LogConnectionStrings) — yedek/manuel kurulum.
-- Tercihen: DataAccess\Migrations\PortalLog\README.txt içindeki "dotnet ef database update --context PortalLogContext".
-- IF NOT EXISTS: mevcut tabloları bozmaz.

CREATE TABLE IF NOT EXISTS "RequestUrl" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Url" text NOT NULL,
    CONSTRAINT "PK_RequestUrl" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Sessions" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserId" bigint NOT NULL,
    "Username" text NOT NULL,
    "Token" text NOT NULL,
    "IPAddress" text NOT NULL,
    "UserAgent" text NOT NULL,
    "SessionHash" text,
    "Verified" boolean NOT NULL,
    CONSTRAINT "PK_Sessions" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "UserActivityLogs" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "SessionId" bigint NOT NULL,
    "RequestUrlId" bigint NOT NULL,
    "Payload" text,
    "StatusCode" integer NOT NULL,
    "Time" timestamp without time zone NOT NULL,
    "Response" text,
    CONSTRAINT "PK_UserActivityLogs" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "StackTrace" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "STHash" text NOT NULL,
    "ErrorStackTrace" text NOT NULL,
    CONSTRAINT "PK_StackTrace" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "ErrorTypes" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Type" text NOT NULL,
    CONSTRAINT "PK_ErrorTypes" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "ErrorMessages" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Message" text,
    CONSTRAINT "PK_ErrorMessages" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Errors" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "ActivityId" bigint NOT NULL,
    "TypeId" bigint NOT NULL,
    "MessageId" bigint NOT NULL,
    "StackTraceId" bigint NOT NULL,
    CONSTRAINT "PK_Errors" PRIMARY KEY ("Id")
);

CREATE INDEX IF NOT EXISTS "IX_UserActivityLogs_Time" ON "UserActivityLogs" ("Time" DESC);
CREATE INDEX IF NOT EXISTS "IX_UserActivityLogs_SessionId" ON "UserActivityLogs" ("SessionId");
CREATE INDEX IF NOT EXISTS "IX_UserActivityLogs_RequestUrlId" ON "UserActivityLogs" ("RequestUrlId");
