-- Haber / duyuru / anket modülü: eksik kolon ve tablolar (idempotent).
-- Yarım kurulmuş dev DB'lerde API 500 (ör. ServiceArea does not exist) önler.
-- Sonrasında: dotnet ef database update --context PortalContext

ALTER TABLE "NewsItems" ADD COLUMN IF NOT EXISTS "ServiceArea" text NULL;
ALTER TABLE "NewsItems" ADD COLUMN IF NOT EXISTS "IsDeleted" boolean NOT NULL DEFAULT false;

ALTER TABLE "Announcements" ADD COLUMN IF NOT EXISTS "ServiceArea" text NULL;
ALTER TABLE "Announcements" ADD COLUMN IF NOT EXISTS "IsDeleted" boolean NOT NULL DEFAULT false;
ALTER TABLE "Announcements" ADD COLUMN IF NOT EXISTS "PublishDate" timestamp without time zone NOT NULL DEFAULT NOW();

ALTER TABLE "Notifications" ADD COLUMN IF NOT EXISTS "NavigationData" text NULL;

CREATE TABLE IF NOT EXISTS "AnnouncementViews" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "AnnouncementId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "ViewedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_AnnouncementViews" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "NewsViews" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "NewsId" bigint NOT NULL,
    "UserId" bigint NOT NULL,
    "ViewedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_NewsViews" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AnnouncementViews_AnnouncementId_UserId"
    ON "AnnouncementViews" ("AnnouncementId", "UserId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_NewsViews_NewsId_UserId"
    ON "NewsViews" ("NewsId", "UserId");
