export const CREATE_FOLDER = "CREATE_FOLDER";
export const ADD_FOLDERS = "ADD_FOLDERS";
export const SET_LOADING = "SET_LOADING";
export const CHANGE_FOLDER = "CHANGE_FOLDER";
export const DELETE_FOLDER = "DELETE_FOLDER";
export const RENAME_FOLDER = "RENAME_FOLDER";

export const COPY_DOCUMENT = "COPY_DOCUMENT";
export const PASTE_DOCUMENT = "PASTE_DOCUMENT";
export const CUT_DOCUMENT = "CUT_DOCUMENT";
export const MOVE_DOCUMENT = "MOVE_DOCUMENT";
//file 
export const ADD_FILES = "ADD_FILES";
export const CREATE_FILE = "CREATE_FILE";
export const SET_FILE_DATA = "SET_FILE_DATA";
export const DELETE_FILE = "DELETE_FILE";
export const RENAME_FILE = "RENAME_FILE";

// emir

export const UPLOAD_DOCUMENT_REQUEST = "UPLOAD_DOCUMENT_REQUEST";
export const UPLOAD_DOCUMENT_SUCCESS = "UPLOAD_DOCUMENT_SUCCESS";
export const UPLOAD_DOCUMENT_FAILURE = "UPLOAD_DOCUMENT_FAILURE";

// actionTypes/fileFoldersActionTypes.js
export const FETCH_DOCUMENTS_REQUEST = "FETCH_DOCUMENTS_REQUEST";
export const FETCH_DOCUMENTS_SUCCESS = "FETCH_DOCUMENTS_SUCCESS";
export const FETCH_DOCUMENTS_FAILURE = "FETCH_DOCUMENTS_FAILURE";

export const CREATE_DOCUMENT_REQUEST = "CREATE_DOCUMENT_REQUEST";
export const CREATE_DOCUMENT_SUCCESS = "CREATE_DOCUMENT_SUCCESS";
export const CREATE_DOCUMENT_FAILURE = "CREATE_DOCUMENT_FAILURE";

export const FOLDER_DOCUMENT_REQUEST = "FOLDER_DOCUMENT_REQUEST";
export const FOLDER_DOCUMENT_SUCCESS = "FOLDER_DOCUMENT_SUCCESS";
export const FOLDER_DOCUMENT_FAILURE = "FOLDER_DOCUMENT_FAILURE";

