import useNotesData from "./useNotesData";
import useNotesActionHandlers from "./useNotesActionHandlers";
import useNotesEditorActions from "./useNotesEditorActions";

export default function useNotesController() {
  const data = useNotesData();

  const actions = useNotesActionHandlers({
    accessToken: data.accessToken,
    activeFolderId: data.activeFolderId,
    allUsers: data.allUsers,
    currentUserId: data.currentUserId,
    folders: data.folders,
    handleUnauthorized: data.handleUnauthorized,
    libraryFilter: data.libraryFilter,
    locale: data.notesLocale,
    notesRef: data.notesRef,
    refreshAllNotes: data.refreshAllNotes,
    selectedNote: data.selectedNote,
    selectedNoteDeleted: data.selectedNoteDeleted,
    selectedNoteId: data.selectedNoteId,
    selectedNoteRef: data.selectedNoteRef,
    setActiveFolderId: data.setActiveFolderId,
    setActiveTagIds: data.setActiveTagIds,
    setFolders: data.setFolders,
    setLibraryFilter: data.setLibraryFilter,
    setNotes: data.setNotes,
    setOpenedFolders: data.setOpenedFolders,
    setEditTagsModalVisible: data.setEditTagsModalVisible,
    setSelectedTagIdsDraft: data.setSelectedTagIdsDraft,
    setSelectedNoteId: data.setSelectedNoteId,
    setSelectedNoteDetail: data.setSelectedNoteDetail,
    setShareModalVisible: data.setShareModalVisible,
    setShareReadOnly: data.setShareReadOnly,
    setShareUserId: data.setShareUserId,
    setSharedNotes: data.setSharedNotes,
    setTrashNotes: data.setTrashNotes,
    setSharedUsersList: data.setSharedUsersList,
    setSharedUsersLoading: data.setSharedUsersLoading,
    sharedUsersList: data.sharedUsersList,
    setTags: data.setTags,
    shareReadOnly: data.shareReadOnly,
    shareUserId: data.shareUserId,
    selectedTagIdsDraft: data.selectedTagIdsDraft,
    tags: data.tags,
    texts: data.texts,
  });

  const editorActions = useNotesEditorActions({
    editorRef: data.editorRef,
    imageInputRef: data.imageInputRef,
    selectedNote: data.selectedNote,
    updateSelectedNote: actions.updateSelectedNote,
  });

  return {
    accessToken: data.accessToken,
    loading: data.loading,
    texts: data.texts,
    sidebar: {
      accessToken: data.accessToken,
      texts: data.texts,
      libraryFilter: data.libraryFilter,
      libraryCounts: data.libraryCounts,
      onCreateNote: actions.handleNewNote,
      onSelectLibrary: actions.handleLibrarySelect,
      onLoadAllNotes: actions.handleLoadAllNotes,
      onLoadSharedNotes: data.refreshSharedNotes,
      folders: data.folders,
      activeFolderId: data.activeFolderId,
      openedFolders: data.openedFolders,
      notesByFolderId: data.notesByFolderId,
      folderCounts: data.folderCounts,
      selectedNoteId: data.selectedNoteId,
      onToggleFolder: actions.toggleFolderOpen,
      onSelectFolder: actions.handleFolderSelect,
      onOpenFolderForNote: actions.openFolderForNote,
      onAddFolder: actions.handleAddFolder,
      onDeleteFolder: actions.handleDeleteFolder,
      tags: data.tags,
      activeTagIds: data.activeTagIds,
      tagUsageCounts: data.tagUsageCounts,
      onToggleTagFilter: actions.toggleTagFilter,
      onRemoveTag: actions.removeTagEverywhere,
      onAddTag: actions.handleAddTag,
    },
    list: {
      texts: data.texts,
      searchText: data.searchText,
      onSearchChange: data.setSearchText,
      sortBy: data.sortBy,
      order: data.order,
      onSortChange: data.setSortByOrder,
      filteredNotes: data.listNotes,
      selectedNoteId: data.selectedNoteId,
      onSelectNote: data.setSelectedNoteId,
      getTagById: data.getTagById,
      libraryFilter: data.libraryFilter,
      sharedNotesLoading: data.sharedNotesLoading,
      sharedSubFilter: data.sharedSubFilter,
      onSharedSubFilterChange: data.setSharedSubFilter,
      trashNotesLoading: data.trashNotesLoading,
      pinnedCount: data.pinnedCount,
      onPinNote: data.handlePinNote,
    },
    editor: {
      texts: data.texts,
      selectedNote: data.selectedNote,
      getTagById: data.getTagById,
      onUpdateNote: actions.updateSelectedNote,
      onSetReminder: actions.setReminderForSelected,
      onDeleteReminder: actions.deleteReminderForSelected,
      onRestore: actions.restoreFromTrash,
      onPermanentlyDelete: actions.permanentlyDeleteSelected,
      onToggleFavorite: actions.toggleFavorite,
      shareMenuItems: actions.shareMenuItems,
      onShareMenuClick: actions.handleShareMenuClick,
      onMoreMenuClick: actions.handleMoreMenuClick,
      moreMenuItems: actions.moreActionsMenuItems,
      onRunEditorCommand: editorActions.runEditorCommand,
      onApplyFontSize: editorActions.applyFontSize,
      onBeforeFontSizeDropdown: editorActions.saveSelectionBeforeFontSize,
      getSelectedFontSize: editorActions.getSelectedFontSize,
      onOpenImagePicker: editorActions.handleInsertImageClick,
      imageInputRef: data.imageInputRef,
      onInsertImage: editorActions.handleInsertImage,
      editorRef: data.editorRef,
      onEditorInput: editorActions.handleEditorInput,
      onEditorKeyDown: editorActions.handleEditorKeyDown,
    },
    modals: {
      texts: data.texts,
      shareModalVisible: data.shareModalVisible,
      shareUserId: data.shareUserId,
      shareReadOnly: data.shareReadOnly,
      sharedUsersList: data.sharedUsersList,
      sharedUsersLoading: data.sharedUsersLoading,
      fetchSharedUsers: actions.fetchSharedUsers,
      toggleSharedUserReadOnly: actions.toggleSharedUserReadOnly,
      removeSharedUser: actions.removeSharedUser,
      editTagsModalVisible: data.editTagsModalVisible,
      allTags: data.tags,
      allUsers: data.allUsers,
      currentUserId: data.currentUserId,
      selectedNoteId: data.selectedNoteId,
      selectedTagIdsDraft: data.selectedTagIdsDraft,
      accessToken: data.accessToken,
      handleUnauthorized: data.handleUnauthorized,
      onShareUserIdChange: data.setShareUserId,
      onShareReadOnlyChange: data.setShareReadOnly,
      onSelectedTagIdsDraftChange: actions.handleSelectedTagIdsDraftChange,
      onCancelShare: actions.closeShareModal,
      onSubmitShare: actions.handleShareNoteSubmit,
      onCancelEditTags: actions.closeEditTagsModal,
      onSubmitEditTags: actions.handleEditTagsSubmit,
    },
  };
}
