using DataAccess.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DataAccess.Concrete.EntityFramework.Context.Migrations
{
    /// <summary>
    /// Sıfırdan kurulum veya dotnet ef database update sonrası portal şemasını idempotent doğrular.
    /// Önceki migration'lar uygulandıysa çoğu satır no-op'tur.
    /// </summary>
    [DbContext(typeof(PortalContext))]
    [Migration("20260520120000_EnsurePortalSchemaComplete")]
    public partial class EnsurePortalSchemaComplete : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
ALTER TABLE ""NewsItems"" ADD COLUMN IF NOT EXISTS ""ServiceArea"" text NULL;
ALTER TABLE ""NewsItems"" ADD COLUMN IF NOT EXISTS ""IsDeleted"" boolean NOT NULL DEFAULT false;

ALTER TABLE ""Announcements"" ADD COLUMN IF NOT EXISTS ""ServiceArea"" text NULL;
ALTER TABLE ""Announcements"" ADD COLUMN IF NOT EXISTS ""IsDeleted"" boolean NOT NULL DEFAULT false;
ALTER TABLE ""Announcements"" ADD COLUMN IF NOT EXISTS ""PublishDate"" timestamp without time zone NOT NULL DEFAULT NOW();

ALTER TABLE ""Notifications"" ADD COLUMN IF NOT EXISTS ""NavigationData"" text NULL;

CREATE TABLE IF NOT EXISTS ""AnnouncementViews"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""AnnouncementId"" bigint NOT NULL,
    ""UserId"" bigint NOT NULL,
    ""ViewedAt"" timestamp without time zone NOT NULL,
    CONSTRAINT ""PK_AnnouncementViews"" PRIMARY KEY (""Id"")
);

CREATE TABLE IF NOT EXISTS ""NewsViews"" (
    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY,
    ""NewsId"" bigint NOT NULL,
    ""UserId"" bigint NOT NULL,
    ""ViewedAt"" timestamp without time zone NOT NULL,
    CONSTRAINT ""PK_NewsViews"" PRIMARY KEY (""Id"")
);

CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AnnouncementViews_AnnouncementId_UserId""
    ON ""AnnouncementViews"" (""AnnouncementId"", ""UserId"");

CREATE UNIQUE INDEX IF NOT EXISTS ""IX_NewsViews_NewsId_UserId""
    ON ""NewsViews"" (""NewsId"", ""UserId"");
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Idempotent doğrulama migration'ı; geri alma desteklenmiyor.
        }
    }
}
