using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Concrete.EntityFramework.Context.Migrations
{
    [Migration("20260602164100_AddRequestSubCategoryFields")]
    public partial class AddRequestSubCategoryFields : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""RequestSubCategoryFields"" (
    ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ""SubCategoryId"" integer NOT NULL,
    ""FieldKey"" text NOT NULL,
    ""Label"" text NOT NULL,
    ""DataType"" text NOT NULL,
    ""IsRequired"" boolean NOT NULL DEFAULT false,
    ""SortOrder"" integer NOT NULL DEFAULT 0,
    ""IsActive"" boolean NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS ""IX_RequestSubCategoryFields_SubCategoryId""
    ON ""RequestSubCategoryFields"" (""SubCategoryId"");

CREATE UNIQUE INDEX IF NOT EXISTS ""IX_RequestSubCategoryFields_SubCategoryId_FieldKey""
    ON ""RequestSubCategoryFields"" (""SubCategoryId"", ""FieldKey"");
");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "RequestSubCategoryFields");
        }
    }
}
