// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DataAccess.Migrations.PortalLog
{
	[DbContext(typeof(PortalLogContext))]
	partial class PortalLogContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "7.0.20")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("Entities.Concrete.Logs.Error", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<long>("ActivityId")
						.HasColumnType("bigint");

					b.Property<long>("MessageId")
						.HasColumnType("bigint");

					b.Property<long>("StackTraceId")
						.HasColumnType("bigint");

					b.Property<long>("TypeId")
						.HasColumnType("bigint");

					b.HasKey("Id");

					b.ToTable("Errors");
				});

			modelBuilder.Entity("Entities.Concrete.Logs.ErrorMessage", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<string>("Message")
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("ErrorMessages");
				});

			modelBuilder.Entity("Entities.Concrete.Logs.ErrorType", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<string>("Type")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("ErrorTypes");
				});

			modelBuilder.Entity("Entities.Concrete.Logs.RequestUrl", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<string>("Url")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("RequestUrl");
				});

			modelBuilder.Entity("Entities.Concrete.Logs.Session", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<string>("IPAddress")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("SessionHash")
						.HasColumnType("text");

					b.Property<string>("Token")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("UserAgent")
						.IsRequired()
						.HasColumnType("text");

					b.Property<long>("UserId")
						.HasColumnType("bigint");

					b.Property<string>("Username")
						.IsRequired()
						.HasColumnType("text");

					b.Property<bool>("Verified")
						.HasColumnType("boolean");

					b.HasKey("Id");

					b.ToTable("Sessions");
				});

			modelBuilder.Entity("Entities.Concrete.Logs.StackTrace", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<string>("ErrorStackTrace")
						.IsRequired()
						.HasColumnType("text");

					b.Property<string>("STHash")
						.IsRequired()
						.HasColumnType("text");

					b.HasKey("Id");

					b.ToTable("StackTrace");
				});

			modelBuilder.Entity("Entities.Concrete.Logs.UserActivity", b =>
				{
					b.Property<long>("Id")
						.ValueGeneratedOnAdd()
						.HasColumnType("bigint");

					NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

					b.Property<string>("Payload")
						.HasColumnType("text");

					b.Property<long>("RequestUrlId")
						.HasColumnType("bigint");

					b.Property<string>("Response")
						.HasColumnType("text");

					b.Property<long>("SessionId")
						.HasColumnType("bigint");

					b.Property<int>("StatusCode")
						.HasColumnType("integer");

					b.Property<DateTime>("Time")
						.HasColumnType("timestamp without time zone");

					b.HasKey("Id");

					b.ToTable("UserActivityLogs");
				});
#pragma warning restore 612, 618
		}
	}
}
